version: '3.7'
services:
  db:
    image: mariadb:10.1
    container_name: coreshop-demo-mariadb
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_file_format=Barracuda, --innodb_large_prefix=1, --innodb_file_per_table=1]
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore
  php:
    build: .
    container_name: coreshop-demo-php
    ports:
     - "80:80"
    links:
     - db:db